import { useEffect, useState } from "react";
import api, { getApiError } from "../api/axios";
export interface OrganizationValue { bidang_id: number | null; sub_bidang_id: number | null; satker_id: number | null }
interface Unit { id: number; bidang_id?: number | null; nama_bidang?: string; nama_sub_bidang?: string; nama_satker?: string }
export default function OrganizationFields({ value, onChange }: { value: OrganizationValue; onChange: (value: OrganizationValue, location: string) => void }) {
    const [data, setData] = useState<{ fields: Unit[]; subs: Unit[]; units: Unit[] }>({ fields: [], subs: [], units: [] });
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState("");
    const [revision, setRevision] = useState(0);
    useEffect(() => { const controller = new AbortController(); setLoading(true); setError(""); Promise.all(["bidangs", "sub-bidangs", "satkers"].map((path) => api.get<{ data: Unit[] }>(`/admin/${path}`, { signal: controller.signal }))).then(([fields, subs, units]) => { if (!controller.signal.aborted) setData({ fields: fields.data.data, subs: subs.data.data, units: units.data.data }); }).catch((err) => { if (!controller.signal.aborted) setError(getApiError(err)); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [revision]);
    function change(next: OrganizationValue) { const location = data.units.find((item) => item.id === next.satker_id)?.nama_satker || data.subs.find((item) => item.id === next.sub_bidang_id)?.nama_sub_bidang || data.fields.find((item) => item.id === next.bidang_id)?.nama_bidang || ""; onChange(next, location); }
    return <section className="organization-fields"><p>Organisasi / penempatan</p><small>Pilihan diambil dari menu Organisasi.</small>{loading ? <p role="status">Memuat organisasi...</p> : error ? <div role="alert"><p>{error}</p><button type="button" className="asset-edit" onClick={() => setRevision((v) => v + 1)}>Coba lagi</button></div> : <><label>Bidang<select value={value.bidang_id ?? ""} onChange={(e) => change({ bidang_id: Number(e.target.value) || null, sub_bidang_id: null, satker_id: null })}><option value="">Belum ditetapkan</option>{data.fields.map((item) => <option key={item.id} value={item.id}>{item.nama_bidang}</option>)}</select></label><label>Subbidang<select disabled={!value.bidang_id} value={value.sub_bidang_id ?? ""} onChange={(e) => change({ ...value, sub_bidang_id: Number(e.target.value) || null })}><option value="">Belum ditetapkan</option>{data.subs.filter((item) => item.bidang_id === value.bidang_id).map((item) => <option key={item.id} value={item.id}>{item.nama_sub_bidang}</option>)}</select></label><label>Satuan kerja / tempat<select value={value.satker_id ?? ""} onChange={(e) => change({ ...value, satker_id: Number(e.target.value) || null })}><option value="">Belum ditetapkan</option>{data.units.filter((item) => !item.bidang_id || item.bidang_id === value.bidang_id).map((item) => <option key={item.id} value={item.id}>{item.nama_satker}</option>)}</select></label>{!data.fields.length && <small>Tambahkan bidang terlebih dahulu melalui menu Organisasi.</small>}</>}</section>;
}
