import { useEffect, useMemo, useState } from "react";
import { Link, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { Plus, X, Check } from "lucide-react";
import { getPortal, saveSubmission, saveThreat, type Asset, type Page, type Submission, type SubmissionInput, type Threat, type NewVulnerability, type SubmissionOptions } from "../../api/satker/portal";
import { useCurrentUser } from "../../routes/RoleGate";
import { getApiError } from "../../api/axios";
import { usePortal, LoadState, PageHeader, Pagination, Confirm } from "../../components/satker/PortalUI";
export default function CreatePengajuan() {
    const user = useCurrentUser();
    const { id } = useParams(); const [params] = useSearchParams(); const navigate = useNavigate();
    const [step, setStep] = useState(0); const [search, setSearch] = useState(""); const [page, setPage] = useState(1);
    const [asset, setAsset] = useState<Asset | null>(null); const [threatIds, setThreatIds] = useState<number[]>([]); const [vulnerabilityIds, setVulnerabilityIds] = useState<number[]>([]); const [custom, setCustom] = useState<NewVulnerability[]>([]); const [notes, setNotes] = useState("");
    const [options, setOptions] = useState<Threat[]>([]); const [availableVulnerabilities, setAvailableVulnerabilities] = useState<SubmissionOptions["vulnerabilities"]>([]); const [optionLoading, setOptionLoading] = useState(false); const [optionError, setOptionError] = useState(""); const [optionRevision, setOptionRevision] = useState(0);
    const [initialLoading, setInitialLoading] = useState(!!id || !!params.get("asset")); const [initialError, setInitialError] = useState(""); const [revision, setRevision] = useState(0);
    const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [confirm, setConfirm] = useState(false);
    const [newName, setNewName] = useState(""); const [newDescription, setNewDescription] = useState(""); const [newThreat, setNewThreat] = useState("");
    const [threatName, setThreatName] = useState("");
    const [threatDescription, setThreatDescription] = useState("");
    async function addThreat() {
        if (!asset || busy || !threatName.trim()) return;
        setBusy(true); setError("");
        try {
            const threat = await saveThreat({ asset_id: asset.id, nama_ancaman: threatName.trim(), deskripsi: threatDescription.trim() });
            setOptions((items) => [...items, threat]);
            setThreatIds((ids) => [...ids, threat.id]);
            setThreatName(""); setThreatDescription("");
        } catch (err) { setError(getApiError(err)); }
        finally { setBusy(false); }
    }
    const assets = usePortal<Page<Asset>>(`assets?scope=reportable&page=${page}&search=${encodeURIComponent(search)}`);
    const preselected = params.get("asset");
    useEffect(() => { const controller = new AbortController(); setInitialError(""); if (id) { setInitialLoading(true); getPortal<Submission>(`pengajuan/${id}`, controller.signal).then((item) => { if (controller.signal.aborted) return; if (item.created_by !== user.id || !["draft", "perlu_perbaikan"].includes(item.status)) throw new Error("Pengajuan ini tidak dapat diedit pada status saat ini."); setAsset(item.asset); setThreatIds(item.threats.map((item) => item.id)); setVulnerabilityIds(item.vulnerabilities.map((item) => item.id)); setCustom(item.new_vulnerabilities || []); setNotes(item.catatan || ""); }).catch((err) => { if (!controller.signal.aborted) setInitialError(getApiError(err)); }).finally(() => { if (!controller.signal.aborted) setInitialLoading(false); }); } else if (preselected) { setInitialLoading(true); getPortal<Asset>(`assets/${preselected}`, controller.signal).then((item) => { if (!controller.signal.aborted) setAsset(item); }).catch((err) => { if (!controller.signal.aborted) setInitialError(getApiError(err)); }).finally(() => { if (!controller.signal.aborted) setInitialLoading(false); }); } return () => controller.abort(); }, [id, preselected, revision, user.id]);
    useEffect(() => { if (!asset) return; const controller = new AbortController(); setOptionLoading(true); setOptionError(""); getPortal<SubmissionOptions>(`options?asset_id=${asset.id}`, controller.signal).then((items) => { if (!controller.signal.aborted) { setOptions(items.threats); setAvailableVulnerabilities(items.vulnerabilities); } }).catch((err) => { if (!controller.signal.aborted) setOptionError(getApiError(err)); }).finally(() => { if (!controller.signal.aborted) setOptionLoading(false); }); return () => controller.abort(); }, [asset?.id, optionRevision]);
    const vulnerabilities = useMemo(() => [...new Map(availableVulnerabilities.map((item) => [item.nama_kerentanan.trim().toLocaleLowerCase(), item])).values()], [availableVulnerabilities]);
    function chooseAsset(item: Asset) { if (item.id !== asset?.id) { setThreatIds([]); setVulnerabilityIds([]); setCustom([]); setOptions([]); setThreatName(""); setThreatDescription(""); } setAsset(item); }
    function toggleThreat(value: number, checked: boolean) { const next = checked ? [...threatIds, value] : threatIds.filter((id) => id !== value); setThreatIds(next); setCustom(custom.map((item) => ({ ...item, threat_ids: item.threat_ids.filter((id) => next.includes(id)) })).filter((item) => item.threat_ids.length)); }
    const ready = !!asset && threatIds.length > 0 && threatIds.every((id) => options.some((item) => item.id === id)) && vulnerabilityIds.every((id) => vulnerabilities.some((item) => item.id === id)) && vulnerabilityIds.length + custom.length > 0 && !optionLoading && !optionError;
    async function save(action: SubmissionInput["action"]) { if (!asset || busy) return; setBusy(true); setError(""); try { const result = await saveSubmission({ asset_id: asset.id, threat_ids: threatIds, vulnerability_ids: vulnerabilityIds, new_vulnerabilities: custom, catatan: notes, action }, id ? Number(id) : undefined); window.dispatchEvent(new Event("satker-notifications")); navigate(`/satker/pengajuan/${result.id}`, { state: { success: action === "draft" ? "Draft berhasil disimpan." : "Pengajuan berhasil dikirim." } }); } catch (err) { setError(getApiError(err)); setConfirm(false); } finally { setBusy(false); } }
    return <><PageHeader title={id ? "Perbaiki pengajuan" : "Buat Pengajuan Risiko"} description="Ceritakan kondisi asset. Penilaian risiko dilakukan oleh pihak yang berwenang." /><LoadState loading={initialLoading} error={initialError} reload={() => setRevision((v) => v + 1)}><div className="sp-wizard-steps" aria-label="Tahapan pengajuan">{["Asset", "Ancaman", "Kerentanan", "Review"].map((label, index) => <div key={label} className={index === step ? "active" : index < step ? "done" : ""} aria-current={index === step ? "step" : undefined}><span>{index < step ? <Check size={15} /> : `0${index + 1}`}</span><strong>{label}</strong></div>)}</div><section className="sp-wizard"><h2>{["Pilih asset", "Pilih ancaman", "Identifikasi kerentanan", "Review pengajuan"][step]}</h2>{step === 0 && <><p>Hanya asset dalam unit kerja Anda yang ditampilkan.</p>{asset && <p className="sp-info">Terpilih: <strong>{asset.nama_aset}</strong></p>}<input aria-label="Cari asset" placeholder="Cari nama atau kode asset..." value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} /><LoadState {...assets}>{assets.data?.data.length ? <><div className="sp-choice-list">{assets.data.data.map((item) => <label key={item.id}><input type="radio" name="asset" checked={asset?.id === item.id} onChange={() => chooseAsset(item)} /><div><strong>{item.nama_aset}</strong><small>{item.kode_aset}</small></div></label>)}</div><Pagination data={assets.data} onPage={setPage} /></> : <p>Belum ada asset. <Link to="/satker/assets/create">Tambah asset</Link></p>}</LoadState></>}
        {step === 1 && <LoadState loading={optionLoading} error={optionError} reload={() => setOptionRevision((v) => v + 1)}><p>Pilih satu atau beberapa ancaman yang sesuai dengan kondisi asset.</p>{options.length ? <div className="sp-choice-list">{options.map((item) => <label key={item.id}><input type="checkbox" checked={threatIds.includes(item.id)} onChange={(e) => toggleThreat(item.id, e.target.checked)} /><strong>{item.nama_ancaman}</strong></label>)}</div> : <p>Belum ada ancaman untuk aset ini. Tambahkan ancaman melalui form di bawah.</p>}<div className="sp-new-vulnerability"><h3>Tambahkan ancaman baru</h3><p>Ancaman disimpan untuk aset ini dan langsung dipilih. Setelah itu, kaitkan dengan kerentanan pada langkah berikutnya.</p><label>Nama ancaman<input maxLength={255} value={threatName} disabled={busy} onChange={(e) => setThreatName(e.target.value)} placeholder="Contoh: Gangguan listrik" /></label><label>Deskripsi<textarea maxLength={5000} value={threatDescription} disabled={busy} onChange={(e) => setThreatDescription(e.target.value)} placeholder="Jelaskan ancaman terhadap aset" /></label><button disabled={busy || !threatName.trim()} onClick={addThreat}><Plus size={16} />{busy ? "Menyimpan..." : "Simpan dan pilih ancaman"}</button></div>{threatIds.some((id) => !options.some((item) => item.id === id)) && <p className="sp-warning">Sebagian ancaman lama tidak lagi tersedia. <button onClick={() => { setThreatIds(threatIds.filter((id) => options.some((item) => item.id === id))); setVulnerabilityIds([]); setCustom([]); }}>Perbarui pilihan</button></p>}</LoadState>}
        {step === 2 && <><p>Kerentanan yang ditampilkan terkait dengan ancaman terpilih.</p><div className="sp-choice-list">{vulnerabilities.map((item) => <label key={item.id}><input type="checkbox" checked={vulnerabilityIds.includes(item.id)} onChange={(e) => setVulnerabilityIds(e.target.checked ? [...vulnerabilityIds, item.id] : vulnerabilityIds.filter((id) => id !== item.id))} /><strong>{item.nama_kerentanan}</strong></label>)}</div>{vulnerabilityIds.some((id) => !vulnerabilities.some((item) => item.id === id)) && <p className="sp-warning">Ada kerentanan yang tidak lagi tersedia. <button onClick={() => setVulnerabilityIds(vulnerabilityIds.filter((id) => vulnerabilities.some((item) => item.id === id)))}>Hapus pilihan tidak tersedia</button></p>}<div className="sp-new-vulnerability"><h3>Identifikasi kerentanan baru</h3><p>Dicatat dalam pengajuan untuk diperiksa reviewer; tidak mengubah master data.</p><label>Nama kerentanan<input maxLength={255} value={newName} onChange={(e) => setNewName(e.target.value)} /></label><label>Ancaman terkait<select value={newThreat} onChange={(e) => setNewThreat(e.target.value)}><option value="">Pilih ancaman</option>{options.filter((item) => threatIds.includes(item.id)).map((item) => <option key={item.id} value={item.id}>{item.nama_ancaman}</option>)}</select></label><label>Deskripsi<textarea maxLength={5000} value={newDescription} onChange={(e) => setNewDescription(e.target.value)} /></label><button disabled={!newName.trim() || !newThreat || custom.length >= 30} onClick={() => { setCustom([...custom, { nama: newName.trim(), deskripsi: newDescription, threat_ids: [Number(newThreat)] }]); setNewName(""); setNewDescription(""); setNewThreat(""); }}><Plus size={16} />Tambahkan ke pengajuan</button></div><ul className="sp-custom-list">{custom.map((item, index) => <li key={index}><div><strong>{item.nama}</strong><small>{item.deskripsi}</small></div><button aria-label={`Hapus ${item.nama} dari pengajuan`} onClick={() => setCustom(custom.filter((_, i) => i !== index))}><X size={16} /></button></li>)}</ul></>}
        {step === 3 && <><dl className="sp-review"><dt>Asset</dt><dd>{asset?.nama_aset}</dd><dt>Ancaman</dt><dd>{options.filter((item) => threatIds.includes(item.id)).map((item) => item.nama_ancaman).join(", ")}</dd><dt>Kerentanan terdaftar</dt><dd>{vulnerabilities.filter((item) => vulnerabilityIds.includes(item.id)).map((item) => item.nama_kerentanan).join(", ") || "Tidak dipilih"}</dd><dt>Identifikasi baru</dt><dd>{custom.map((item) => item.nama).join(", ") || "Tidak ada"}</dd></dl><label>Catatan tambahan<textarea rows={4} maxLength={10000} value={notes} onChange={(e) => setNotes(e.target.value)} /></label><p className="sp-info">Setelah dikirim, pengajuan ditinjau oleh Kasub. Anda dapat mengedit kembali jika diminta melakukan perbaikan.</p></>}
        {error && <p className="sp-error" role="alert">{error}</p>}<div className="sp-wizard-actions"><button disabled={step === 0 || busy} onClick={() => setStep(step - 1)}>Kembali</button><div><button disabled={!asset || busy || optionLoading || !!optionError} onClick={() => save("draft")}>Simpan draft</button>{step < 3 ? <button className="sp-primary" disabled={busy || !asset || (step === 1 && (!threatIds.length || optionLoading || !!optionError)) || (step === 2 && !ready)} onClick={() => setStep(step + 1)}>Lanjutkan</button> : <button className="sp-primary" disabled={busy || !ready} onClick={() => setConfirm(true)}>Kirim pengajuan</button>}</div></div></section>{confirm && <Confirm title="Kirim pengajuan risiko?" busy={busy} onCancel={() => setConfirm(false)} onConfirm={() => save("submit")}><p>Pastikan asset, ancaman, dan kerentanan sudah sesuai. Pengajuan akan dikirim untuk ditinjau Kasub.</p></Confirm>}</LoadState></>;
}
