import { useEffect, useState, type FormEvent } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { getPortal, saveAsset, type Asset, type SatkerAssetInput } from "../../api/satker/portal";
import { getApiError } from "../../api/axios";
import { useCurrentUser } from "../../routes/RoleGate";
import { PageHeader } from "../../components/satker/PortalUI";
export default function CreateAsset() { const { id } = useParams(); const navigate = useNavigate(); const user = useCurrentUser(); const [form, setForm] = useState<SatkerAssetInput>({ nama_aset: "", kategori: "physical", kondisi: "", deskripsi: "", idx: null, jumlah: 1, merk: "", snumber: "", pengadaan: "", nilai_kekritisan: null }); const [loading, setLoading] = useState(!!id); const [error, setError] = useState(""); const [loadError, setLoadError] = useState(""); const [revision, setRevision] = useState(0); const [busy, setBusy] = useState(false); useEffect(() => { if (!id) return; const controller = new AbortController(); setLoading(true); setLoadError(""); getPortal<Asset>(`assets/${id}`, controller.signal).then((asset) => { if (controller.signal.aborted) return; if (!asset.permissions.can_edit) { setLoadError("Anda hanya dapat mengedit asset buatan sendiri."); return; } setForm({ nama_aset: asset.nama_aset, kategori: asset.kategori, kondisi: asset.kondisi || "baik", deskripsi: asset.deskripsi || "", idx: asset.idx ?? null, jumlah: asset.jumlah ?? 1, merk: asset.merk || "", snumber: asset.snumber || "", pengadaan: asset.pengadaan || "", nilai_kekritisan: asset.nilai_kekritisan ?? null }); }).catch((err) => { if (!controller.signal.aborted) setLoadError(getApiError(err)); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [id, revision]); async function submit(event: FormEvent) { event.preventDefault(); if (busy || loading || loadError) return; setBusy(true); setError(""); try { const asset = await saveAsset(form, id ? Number(id) : undefined); navigate(`/satker/assets/${asset.id}`, { state: { success: "Asset berhasil disimpan." } }); } catch (err) { setError(getApiError(err)); } finally { setBusy(false); } } return <><PageHeader title={id ? "Edit asset" : "Tambah asset"} description="Catat informasi asset yang menjadi tanggung jawab unit Anda." /><form className="sp-form sp-asset-form" onSubmit={submit}><p className="sp-info">Penempatan otomatis: {user.sub_bidang?.nama_sub_bidang} / {user.satker?.nama_satker}. Kepemilikan ditentukan oleh sistem.</p>{loading ? <p role="status">Memuat asset...</p> : loadError ? <div role="alert"><p>{loadError}</p><button type="button" onClick={() => setRevision((v) => v + 1)}>Coba lagi</button></div> : <>            <label>ID inventaris eksternal (idx)<input type="number" min={1} max={2147483647} step={1} placeholder="Opsional, contoh: 257" value={form.idx ?? ""} onChange={(event) => setForm({ ...form, idx: event.target.value === "" ? null : event.target.valueAsNumber })} /></label>
            <label>Stok / jumlah aset *<input type="number" required min={1} max={2147483647} step={1} value={Number.isNaN(form.jumlah) ? "" : form.jumlah} onChange={(event) => setForm({ ...form, jumlah: event.target.valueAsNumber })} /><small>Jumlah unit aset, minimal 1.</small></label><label>Nama aset *<input autoFocus required maxLength={255} placeholder="Nama aset" value={form.nama_aset} onChange={(event) => setForm({ ...form, nama_aset: event.target.value })} /></label>
            <div className="sp-form-row"><label>Kategori *<select value={form.kategori} onChange={(event) => setForm({ ...form, kategori: event.target.value })}>{Object.entries({ physical: "Fisik", software: "Perangkat lunak", digital: "Digital" }).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>
            <label>Nilai kekritisan<select value={form.nilai_kekritisan ?? ""} onChange={(event) => setForm({ ...form, nilai_kekritisan: event.target.value ? Number(event.target.value) : null })}><option value="">Belum dinilai</option>{[1, 2, 3, 4, 5].map((value) => <option key={value} value={value}>{value} / 5</option>)}</select></label></div>
            <div className="sp-form-row"><label>Kondisi<input maxLength={100} placeholder="Contoh: Baik" value={form.kondisi || ""} onChange={(event) => setForm({ ...form, kondisi: event.target.value })} /></label><label>Merk<input maxLength={255} value={form.merk || ""} onChange={(event) => setForm({ ...form, merk: event.target.value })} /></label></div>
            <label>Serial number (snumber)<input maxLength={255} value={form.snumber || ""} onChange={(event) => setForm({ ...form, snumber: event.target.value })} /></label>
<div className="sp-form-row"><label>Bidang<input readOnly value={user.bidang?.nama_bidang || ""} /></label><label>Subbidang<input readOnly value={user.sub_bidang?.nama_sub_bidang || ""} /></label></div><label>Satuan kerja<input readOnly value={user.satker?.nama_satker || ""} /></label>
            <div className="sp-form-row"><label>Tanggal pengadaan<input type="date" min="1000-01-01" max="9999-12-31" value={form.pengadaan || ""} onChange={(event) => setForm({ ...form, pengadaan: event.target.value })} /></label><label>Lokasi organisasi<input readOnly value={user.satker?.nama_satker || ""}  /></label></div>
            <label>Keterangan<textarea maxLength={10000} rows={3} placeholder="Informasi tambahan mengenai aset" value={form.deskripsi || ""} onChange={(event) => setForm({ ...form, deskripsi: event.target.value })} /></label>
</>}{error && <p className="sp-error" role="alert">{error}</p>}<div className="sp-actions"><Link to={id ? `/satker/assets/${id}` : "/satker/assets"}>Kembali</Link><button className="sp-primary" disabled={busy || loading || !!loadError || !user.satker_id || !user.sub_bidang_id}>{busy ? "Menyimpan..." : "Simpan asset"}</button></div></form></>; }
