import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import { dateText, type Assessment, type Page, type Treatment } from "../../api/satker/portal";
import api, { getApiError } from "../../api/axios";
import { useCurrentUser } from "../../routes/RoleGate";
import { usePortal, LoadState, PageHeader, Empty, StatusBadge, Pagination, Confirm } from "../../components/satker/PortalUI";
export function TreatmentCard({ item, reload }: { item: Treatment; reload: () => void }) { const user = useCurrentUser(); const [progress, setProgress] = useState("proses"); const [notes, setNotes] = useState(""); const [confirm, setConfirm] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const canUpdate = !!item.approved_by && !!item.approved_at && item.pic === user.id && item.status !== "selesai"; async function save() { setBusy(true); setError(""); try { await api.patch(`/satker/treatments/${item.id}/progress`, { status: progress, catatan: notes }); setConfirm(false); setSuccess("Progres treatment berhasil diperbarui."); window.dispatchEvent(new Event("satker-notifications")); reload(); } catch (err) { setError(getApiError(err)); setConfirm(false); } finally { setBusy(false); } } return <section className="sp-treatment"><div className="sp-card-top"><h3>Treatment: {item.strategi}</h3><StatusBadge status={item.status} /></div><p>Target: {dateText(item.target_selesai)}</p><p>{item.catatan || "Belum ada catatan."}</p><small>{item.approved_at ? "Disetujui Kasub" : "Menunggu persetujuan Kasub"}</small>{success && <p className="sp-success" role="status">{success}</p>}{canUpdate && <div className="sp-treatment-form"><label>Progres<select value={progress} onChange={(e) => setProgress(e.target.value)}><option value="proses">Dalam proses</option><option value="selesai">Selesai</option></select></label><label>Catatan progres<textarea maxLength={10000} value={notes} onChange={(e) => setNotes(e.target.value)} /></label><button disabled={!notes.trim() || busy} onClick={() => setConfirm(true)}>Perbarui progres</button></div>}{error && <p className="sp-error" role="alert">{error}</p>}{confirm && <Confirm title="Perbarui progres treatment?" busy={busy} onCancel={() => setConfirm(false)} onConfirm={save}><p>Progres akan disimpan sebagai {progress === "selesai" ? "selesai" : "dalam proses"}.</p></Confirm>}</section>; }
export function AssessmentView({ item, reload }: { item: Assessment; reload: () => void }) { return <section className="sp-section"><div className="sp-section-title"><h2>Hasil risk assessment</h2><StatusBadge status={item.level} /></div><div className="sp-score-row"><div><span>Kemungkinan</span><strong>{item.likelihood}<small> / 5</small></strong></div><div><span>Dampak</span><strong>{item.impact}<small> / 5</small></strong></div><div><span>Skor risiko</span><strong>{item.skor}</strong></div></div><p>Ancaman: {(item.threats?.length ? item.threats : item.threat ? [item.threat] : []).map((value) => value.nama_ancaman).join(", ")}</p><p>Kerentanan: {item.vulnerabilities?.map((value) => value.nama_kerentanan).join(", ") || "Belum dicatat"}</p><p>{item.catatan}</p><small>Dinilai oleh {item.dinilai_oleh?.name || "Penilai"} ? {dateText(item.tanggal_penilaian)}</small><h3 className="sp-subheading">Risk treatment</h3>{item.treatments.length ? item.treatments.map((treatment) => <TreatmentCard key={treatment.id} item={treatment} reload={reload} />) : <p className="sp-muted">Belum ada treatment yang ditetapkan.</p>}</section>; }
export function RiskAssessmentDetail() { const { id } = useParams(); const state = usePortal<Assessment>(`risk-assessments/${id}`); return <><PageHeader title="Detail assessment" description="Hasil penilaian oleh pihak yang berwenang." /><LoadState {...state}>{state.data && <><Link to={`/satker/assets/${state.data.asset.id}`}>{state.data.asset.nama_aset}</Link><AssessmentView item={state.data} reload={state.reload} /></>}</LoadState></>; }
export default function RiskAssessments() { const [page, setPage] = useState(1); const state = usePortal<Page<Assessment>>(`risk-assessments?page=${page}`); return <><PageHeader title="Hasil Risk Assessment" description="Lihat tingkat risiko dan tindak lanjut asset unit Anda." /><LoadState {...state}>{state.data?.data.length ? <><div className="sp-card-grid">{state.data.data.map((item) => <article className="sp-card" key={item.id}><StatusBadge status={item.level} /><h3>{item.asset.nama_aset}</h3><p>Skor {item.skor} ? {dateText(item.tanggal_penilaian)}</p><Link to={`/satker/risk-assessments/${item.id}`}>Lihat hasil & treatment</Link></article>)}</div><Pagination data={state.data} onPage={setPage} /></> : <Empty title="Belum ada hasil assessment"><p>Hasil penilaian akan tampil setelah assessment selesai.</p></Empty>}</LoadState></>; }
