import { useCallback, useEffect, useRef, useState, type ReactNode } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, Box, Check, AlertCircle, ChevronLeft, ChevronRight } from "lucide-react";
import { getPortal, dateText, type Asset, type Submission, type Page } from "../../api/satker/portal";
import { getApiError } from "../../api/axios";
export function usePortal<T>(path: string) { const [data, setData] = useState<T | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [revision, setRevision] = useState(0); useEffect(() => { const controller = new AbortController(); setLoading(true); setError(""); getPortal<T>(path, controller.signal).then((result) => { if (!controller.signal.aborted) setData(result); }).catch((err) => { if (!controller.signal.aborted) setError(getApiError(err)); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [path, revision]); return { data, error, loading, reload: useCallback(() => setRevision((v) => v + 1), []) }; }
export function LoadState({ loading, error, reload, children }: { loading: boolean; error: string; reload: () => void; children: ReactNode }) { if (loading) return <div className="sp-loading" role="status"><span /><span /><p>Memuat data...</p></div>; if (error) return <div className="sp-empty" role="alert"><AlertCircle /><h3>Data belum dapat dimuat</h3><p>{error}</p><button onClick={reload}>Coba lagi</button></div>; return <>{children}</>; }
export const statuses: Record<string, string> = { draft: "Draft", diajukan: "Diajukan", ditinjau: "Ditinjau", perlu_perbaikan: "Perlu perbaikan", disetujui: "Disetujui", ditolak: "Ditolak", selesai: "Selesai", belum: "Belum dimulai", proses: "Dalam proses", active: "Aktif", inactive: "Tidak aktif", rendah: "Rendah", sedang: "Sedang", tinggi: "Tinggi", sangat_tinggi: "Tinggi", ekstrem: "Tinggi" };
export function StatusBadge({ status }: { status: string }) { return <span className={`sp-badge sp-status-${status}`}>{statuses[status] || status}</span>; }
export function Empty({ title, children }: { title: string; children?: ReactNode }) { return <div className="sp-empty"><Box size={30} /><h3>{title}</h3>{children}</div>; }
export function PageHeader({ title, description, action }: { title: string; description: string; action?: ReactNode }) { return <div className="sp-page-header"><div><span className="sp-eyebrow">PORTAL SATKER</span><h1>{title}</h1><p>{description}</p></div>{action}</div>; }
export function AssetCard({ asset }: { asset: Asset }) { const activeRisks = (asset.risk_assessments || []).filter((risk) => !risk.treatments.length || risk.treatments.some((treatment) => treatment.status !== "selesai")); const threatNames = [...new Set(activeRisks.flatMap((risk) => (risk.threats?.length ? risk.threats : risk.threat ? [risk.threat] : []).map((threat) => threat.nama_ancaman)))]; return <article className="sp-card"><div className="sp-card-top"><span className="sp-icon"><Box size={22} /></span><StatusBadge status={asset.status} /></div><h3>{asset.nama_aset}</h3><p className="sp-code">{asset.kode_aset}</p><p>{asset.permissions.can_edit ? "Ditambahkan oleh Anda" : asset.satker_id === null ? "Asset bersama subbidang" : `Ditambahkan oleh ${asset.creator?.name || "unit kerja"}`}</p><p>Lokasi: {asset.lokasi || asset.satker?.nama_satker || "Belum dicatat"}</p><div className="sp-card-meta"><span>Kondisi: {asset.kondisi || "Belum dicatat"}</span>{asset.has_active_risk ? <StatusBadge status={asset.risk_level || "tinggi"} /> : <span>Tanpa risiko aktif</span>}</div>{asset.has_active_risk && <div><p className="sp-risk-note">Ancaman: {threatNames.join(", ") || "Lihat detail risiko"}</p><p>Treatment: {activeRisks.some((risk) => !risk.treatments.length) ? "Belum ditetapkan" : activeRisks.some((risk) => risk.treatments.some((treatment) => treatment.status === "proses")) ? "Dalam proses" : "Belum dimulai"}</p></div>}<div className="sp-card-actions"><Link to={`/satker/assets/${asset.id}`}>Lihat detail <ArrowRight size={15} /></Link>{asset.permissions.can_edit && <Link className="sp-secondary" to={`/satker/assets/${asset.id}/edit`}>Edit</Link>}</div></article>; }
export function SubmissionReporter({ item }: { item: Submission }) {
    return <dl className="sp-submission-reporter">
        <div><dt>Pelapor</dt><dd>{item.creator?.name || "Tidak tercatat"}</dd></div>
        <div><dt>Satuan kerja</dt><dd>{item.satker?.nama_satker || "Tidak tercatat"}</dd></div>
    </dl>;
}
export function PengajuanCard({ item }: { item: Submission }) {
    return <article className="sp-submission">
        <div className="sp-submission-info">
            <span className="sp-code">PENGAJUAN #{item.id}</span>
            <h3>{item.asset?.nama_aset || "Aset tidak tersedia"}</h3>
            <SubmissionReporter item={item} />
            <div className="sp-submission-threats"><span>Ancaman</span><div>{item.threats.length ? item.threats.map((threat) => <span key={threat.id}>{threat.nama_ancaman}</span>) : <small>Belum dipilih</small>}</div></div>
            <div className="sp-submission-dates"><span>Dibuat: {dateText(item.created_at)}</span><span>Diperbarui: {dateText(item.updated_at)}</span></div>
        </div>
        <div className="sp-submission-actions"><StatusBadge status={item.status} /><Link to={`/satker/pengajuan/${item.id}`}>Lihat detail <ArrowRight size={15} /></Link></div>
    </article>;
}
export function Pagination({ data, onPage }: { data: Page<unknown>; onPage: (page: number) => void }) { return <div className="sp-pagination"><span>{data.total} data &middot; Halaman {data.current_page} / {data.last_page}</span><div><button aria-label="Halaman sebelumnya" disabled={data.current_page <= 1} onClick={() => onPage(data.current_page - 1)}><ChevronLeft size={18} /></button><button aria-label="Halaman berikutnya" disabled={data.current_page >= data.last_page} onClick={() => onPage(data.current_page + 1)}><ChevronRight size={18} /></button></div></div>; }
export function Timeline({ item }: { item: Submission }) { const pending = item.status === "ditolak" ? [] : [!item.assessment && "Risk Assessment", item.status !== "selesai" && "Risk Treatment", item.status !== "selesai" && "Selesai"].filter(Boolean); return <ol className="sp-timeline">{item.timeline.map((event, index) => <li key={index}><span><Check size={13} /></span><div><strong>{event.label}</strong><small>{dateText(event.at)}</small></div></li>)}{pending.map((label) => <li className="pending" key={String(label)}><span /><div>{label}</div></li>)}</ol>; }
export function Confirm({ title, busy, onCancel, onConfirm, children }: { title: string; busy: boolean; onCancel: () => void; onConfirm: () => void; children: ReactNode }) { const ref = useRef<HTMLDialogElement>(null); useEffect(() => { const element = ref.current; element?.showModal(); return () => element?.close(); }, []); return <dialog className="sp-confirm" ref={ref} aria-label={title} onCancel={(event) => { event.preventDefault(); if (!busy) onCancel(); }}><h2>{title}</h2>{children}<div className="sp-actions"><button disabled={busy} onClick={onCancel}>Batal</button><button className="sp-primary" disabled={busy} onClick={onConfirm}>{busy ? "Menyimpan..." : "Ya, lanjutkan"}</button></div></dialog>; }
